const MONSTER_CLASSES = Object.freeze({
    DIVING_MONSTER: 'Diving Monster',
    FLYING_MONSTER: 'Flying Monster',
    INSECT_MONSTER: 'Insect Monster',
    FIRE_MONSTER: 'Fire Monster',
    WATER_MONSTER: 'Water Monster',
    ELECTRIC_MONSTER: 'Electric Monster',
    PSYCHIC_MONSTER: 'Psychic Monster',
    GRASS_MONSTER: 'Grass Monster'
})

const LIST_OF_MONSTER_CLASSES = Object.freeze([
    MONSTER_CLASSES.DIVING_MONSTER,
    MONSTER_CLASSES.FLYING_MONSTER,
    MONSTER_CLASSES.INSECT_MONSTER,
    MONSTER_CLASSES.FIRE_MONSTER,
    MONSTER_CLASSES.WATER_MONSTER,
    MONSTER_CLASSES.ELECTRIC_MONSTER,
    MONSTER_CLASSES.PSYCHIC_MONSTER,
    MONSTER_CLASSES.GRASS_MONSTER,
])

export {
    LIST_OF_MONSTER_CLASSES,
    MONSTER_CLASSES,

} 